version: '3.4'

services: 
    proxy:
        image: ${DOCKER_REGISTRY-}proxy
        build:
            context: ./Proxy
            dockerfile: Dockerfile
        ports: 
            - "80:80"
    client:
        image: ${DOCKER_REGISTRY-}client
        build:
            context: ./ClientApp
            dockerfile: Dockerfile
        ports:
            - "9000:80"
    api:
        image: ${DOCKER_REGISTRY-}api
        build:
            context: .
            dockerfile: LongRunningJobImitator/Dockerfile
        ports: 
            - "5000:80"
            - "5001:443"
