version: '3.4'

services: 
    mongo:
        image: mongo

    textconverterapi:
        image: ${DOCKER_REGISTRY-}api
        build:
            context: .
            dockerfile: LongRunningJobImitator.Api/Dockerfile
        depends_on:
            - mongo

    backgroundservices:
        image: ${DOCKER_REGISTRY-}backgroundservices
        build:
            context: ./LongRunningJobImitator.BackgroundServices
            dockerfile: Dockerfile
        depends_on:
            - mongo

    client:
        image: ${DOCKER_REGISTRY-}client
        build:
            context: ./ClientApp
            dockerfile: Dockerfile
        depends_on:
            - textconverterapi

    nginx:
        image: ${DOCKER_REGISTRY-}nginx
        build:
            context: ./Nginx
            dockerfile: Dockerfile
    
