version: '3.4'

services: 
    mongo:
        image: mongo

    textconverterapi:
        image: ${DOCKER_REGISTRY-}api
        build:
            context: .
            dockerfile: LongRunningJobImitator.Api/Dockerfile
        depends_on:
            - mongo

    client:
        image: ${DOCKER_REGISTRY-}client
        build:
            context: ./ClientApp
            dockerfile: Dockerfile
        depends_on:
            - textconverterapi
