version: '3.4'

services: 
    client:
        image: ${DOCKER_REGISTRY-}client
        build:
            context: ./ClientApp
            dockerfile: Dockerfile
        ports:
            - "9000:80"
    textconverterapi:
        image: ${DOCKER_REGISTRY-}api
        build:
            context: .
            dockerfile: LongRunningJobImitator.Api/Dockerfile
        ports:
            - "5000:80"
            - "5001:433"
