version: '3.4'

services:
    textconverterapi:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - Database__ConnectionString=mongodb://mongo:27017
            - JobApi__Url=http://backgroundservices:80
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        ports:
            - "5000:80"
            - "5001:443"

    backgroundservices:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - Database__ConnectionString=mongodb://mongo:27017
            - SignalRHub__Url=http://textconverterapi:80
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    mongo:
        ports:
            - "27018:27017"

    client:
        ports:
            - "9000:80"